FROM ubuntu:22.04

# OpenMPI/4.1.4-GCC-11.3.0

# docker build -f Dockerfile.svsolver-openmpi-4.14 -t jmwarfe/svsolver:openmpi-4.14 .
# docker push jmwarfe/svsolver
# singularity pull docker://jmwarfe/svsolver:openmpi-4.14

LABEL Maintainer jmwarfe@case.edu
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y git apt-utils wget gcc mpich gfortran cmake lsb-core

WORKDIR /code

# Prepare for install, file shouldn't have "sudo" hard-coded in it
RUN git clone https://github.com/SimVascular/svSolver.git && \
    cd svSolver/BuildWithMake && \
    rm -rf quick-build-linux.sh && \
    wget https://github.com/jmwarfe/simvascular/raw/master/quick-build-linux.sh && \
    /bin/bash quick-build-linux.sh

# Install some version of open MPI https://www.open-mpi.org/software/ompi/v4.0/
RUN wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.4.tar.gz && \
    tar -xzvf openmpi-4.1.4.tar.gz && \
    cd openmpi-4.1.4 && \
    ./configure --prefix=/usr/local && \
    make && \
    make install

# Binaries (with .exe extensions?) are here
ENV PATH /code/svSolver/BuildWithMake/Bin:$PATH
ENTRYPOINT ["svsolver-nompi.exe"]
